### ISSUE TITLE
Feature Request: Custom Handlers

### ISSUE THREAD

**Issue by fuma-nama** [remcohaszing/estree-util-value-to-estree#4]
## Feature

I want to be able to customise how `valueToEstree` converts an object to estree.

The solution I'm thinking of, would be providing an `handlers` option for handling different types.

For example, disable it only for objects containing a special property.

```ts
valueToEstree(value, {
  handlers: {
    object: (v) => isHast(v)? hastToEstree(v) : undefined
  |
})
```

When `undefined` is returned, use the default behavour.

## Additional context

I was trying to inject an object as the prop of a MDX element. Now I have an object like:

```jsx
{
  name: "Hello",
  description: "Markdown Content"
}
```

to convert it into estree, I have to first compile the markdown content `description` to HAST tree, and use `hast-util-to-estree` to make it an estree.

```jsx
{
  name: "Hello",
  description: { ... } // ES Tree
}
```

Now I will use this utility to convert the whole object into estree. But it apparently will treat the `description` property as an ordinary object, hence it can't give my desired result.

I fixed it by manipulating the estree afterwards, would like to see if this can be done with this library.

**Comment by remcohaszing** [comment]
Let’s take a step back. This sounds like an [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).

You have an object that has two properties: name (a string) and description (an ESTree expression). What is this object? It seems you don’t want to turn the entire object into an ESTree expression. You could use this instead:

```js
function processYourSpecificObject(object) {
  return {
    type: 'ObjectExpression',
    properties: [
      {
        type: 'Property',
        computed: false,
        method: false,
        kind: 'init',
        shorthand: false,
        key: { type: 'Identifier', name: 'name' },
        value: { type: 'Literal', value: object.name }
      },
      {
        type: 'Property',
        computed: false,
        method: false,
        kind: 'init',
        shorthand: false,
        key: { type: 'Identifier', name: 'description' },
        value: descriptionToEstree(object.description)
      }
    ]
  }
}
```

I have a hunch maybe you’re looking for [`hast-util-properties-to-mdx-jsx-attributes`](https://github.com/remcohaszing/hast-util-properties-to-mdx-jsx-attributes). It’s just a hunch, I don’t have a lot of context.

I like your idea to add support for custom classes and your willingness to provide a PR. But using the `Ignore` class is more of a hack abusing this feature than the actual solution you’re looking for. For custom classes we’d really need to think about how to handle ordering, finalizers, recursion, inter-class, and inter-instance dependencies.

**Comment by fuma-nama** [comment]
Thanks for your help! It's indeed what I have came up with. Unfortunately [`hast-util-properties-to-mdx-jsx-attributes`](https://github.com/remcohaszing/hast-util-properties-to-mdx-jsx-attributes) doesn't seems to fit my use case, I will close this as the workaround is working great now.
